# Generated by Django 2.0 on 2017-12-26 16:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='article title')),
                ('content', ckeditor.fields.RichTextField(max_length=30000, verbose_name='article content')),
                ('created', models.DateTimeField(verbose_name='article created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='article updated')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='article slug')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='article description')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='category name')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='category slug')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='category description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='article_app.Category', verbose_name='related category'),
        ),
    ]
