# Generated by Django 2.0 on 2017-12-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_auto_20171226_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='name')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('user_url', models.URLField(blank=True, verbose_name='website')),
                ('content', models.TextField(verbose_name='comment')),
                ('created', models.DateTimeField(blank=True, verbose_name='comment created')),
                ('is_approved', models.BooleanField(default=False, verbose_name='comment approved')),
                ('article', models.ForeignKey(on_delete=None, to='article_app.Article', verbose_name='related article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=None, to='article_app.Comment', verbose_name='parent comment')),
            ],
            options={
                'verbose_name_plural': 'comments',
                'ordering': ['-created'],
                'verbose_name': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='setting name')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='setting value')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='setting description')),
            ],
            options={
                'verbose_name_plural': 'settings',
                'verbose_name': 'setting',
            },
        ),
        migrations.CreateModel(
            name='SpamSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.CharField(max_length=255, unique=True, verbose_name='snippet')),
            ],
            options={
                'verbose_name_plural': 'spam snippets',
                'verbose_name': 'spam snippet',
            },
        ),
    ]
