# Generated by Django 2.0 on 2017-12-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_comment_setting_spamsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_comment_allowed',
            field=models.BooleanField(default=True, verbose_name='comment allowed'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='article published'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_standalone',
            field=models.BooleanField(default=False, verbose_name='standalone page'),
        ),
    ]
