# Generated by Django 2.0 on 2017-12-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0004_auto_20171226_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='snippet name')),
                ('content', models.TextField(verbose_name='snippet content')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='snippet description')),
            ],
            options={
                'verbose_name': 'template snippet',
                'verbose_name_plural': 'template snippets',
            },
        ),
    ]
