# Generated by Django 2.0 on 2018-01-08 11:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0005_templatesnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', max_length=30000, verbose_name='article content'),
        ),
    ]
